# Generated by Django 2.2.5 on 2019-09-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0003_auto_20190924_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area_hectares',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
